---
name: Pytest
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ckan-version: ['2.11', '2.10', 2.9]
        experimental: [false]
        include:
          - ckan-version: 'master'
            experimental: true  # master is unstable, good to know if we are compatible or not

    name: ${{ matrix.experimental && '**Fail_Ignored** ' || '' }} CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}
      SOLR_VERSION: ${{ matrix.solr-version }}

    steps:
      - name: Install Ahoy and dependencies
        continue-on-error: ${{ matrix.experimental }}
        run: |
          sudo wget https://github.com/ahoy-cli/ahoy/releases/download/v2.5.0/ahoy-bin-linux-amd64 -O /usr/local/bin/ahoy \
            && sudo chown $USER /usr/local/bin/ahoy \
            && chmod +x /usr/local/bin/ahoy
          sudo wget https://github.com/pygmystack/pygmy/releases/download/v0.14.0/pygmy_0.14.0_linux_amd64.tar.gz -O - | tar xvzf - -C /tmp/ \
            && sudo mv /tmp/pygmy /usr/local/bin/pygmy

      - uses: actions/checkout@v7
        continue-on-error: ${{ matrix.experimental }}
        timeout-minutes: 2

      - name: Build
        run: bin/build.sh
        timeout-minutes: 15
        continue-on-error: ${{ matrix.experimental }}

      - name: Test
        run: bin/test.sh
        timeout-minutes: 15
        continue-on-error: ${{ matrix.experimental }}

      - name: Retrieve logs
        if: always()
        run: ahoy logs
        timeout-minutes: 1
        continue-on-error: ${{ matrix.experimental }}

      - name: Retrieve results
        if: always()
        run: bin/process-artifacts.sh
        timeout-minutes: 1
        continue-on-error: true #don't fail if we can't upload (ie a fork that does not have integration plugged in)

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CKAN ${{ matrix.ckan-version }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
        continue-on-error: true

      - name: Pytest Coverage Console Report
        if: ${{ !cancelled() }}
        continue-on-error: true
        run: |
          set -ex
          ahoy cli "coverage report -m"

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: combined-test-coverage-reports-${{ matrix.ckan-version }}
          path: /tmp/artifacts/junit

      - name: Test Summary
        uses: test-summary/action@v2
        continue-on-error: true
        with:
          paths: "/tmp/artifacts/junit/results.xml"
        if: ${{ !cancelled() }}

      - name: Install packages required for codecov
        if: ${{ !cancelled() }}
        continue-on-error: true
        run: |
          # ubuntu based images
          apt-get install -y --no-install-recommends curl gpg

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/artifacts/junit/coverage.xml
          verbose: false # optional (default = false)

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        if: ${{ !cancelled() }}
        continue-on-error: true #don't fail if we can't upload (ie a fork that does not have integration plugged in)
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/artifacts/junit/results.xml
          verbose: false # optional (default = false)

